version: "3.8"

services:
  jobmanager:
    image: flink-with-kafka-trad:2.0
    command: jobmanager
    ports:
      - "8081:8081"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      - flink_net
      - kafka_network
    deploy:
      placement:
        constraints: [node.role == manager]

  taskmanager:
    image: flink-with-kafka-trad:2.0
    command: taskmanager
    depends_on:
      - jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      - flink_net
      - kafka_network
    deploy:
      replicas: 2

networks:
  flink_net:
    driver: overlay
  kafka_network:
    external: true
