version: "3.8"

services:
  jobmanager:
    image: iot-stream-flink-benchmark_local
    command: jobmanager
    ports:
      - "8081:8081"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      - flink_net
      - kafka_network
    deploy:
      placement:
        constraints: [node.role == manager]

  taskmanager:
    image: iot-stream-flink-benchmark_local
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      - flink_net
      - kafka_network
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
  

networks:
  flink_net: {}
  kafka_network:
    external: true
