version: "3.8"

services:
  kafka:
    image: confluentinc/cp-kafka:7.7.0
    hostname: kafka
    ports:
      - "9092:9092" # Isso está correto (Host 9092 -> Container 9092)
    environment:
      # Identificação do cluster
      CLUSTER_ID: "abcdefghijklmnopqrstuv"

      # Configuração KRaft (sem ZooKeeper)
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # Listeners (O que o Kafka "ouve")
      # Vamos usar um listener "ALL" para simplificar
      KAFKA_LISTENERS: "ALL://:9092,CONTROLLER://:9093" # <-- MUDANÇA 1

      # Advertised Listeners (O que o Kafka "anuncia" para o mundo)
      # Esta é a correção principal:
      # Anuncie o IP do HOST para TODOS os clientes.
      KAFKA_ADVERTISED_LISTENERS: "ALL://172.16.16.3:9092" # <-- MUDANÇA 2

      # Mapa de protocolos
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "ALL:PLAINTEXT,CONTROLLER:PLAINTEXT" # <-- MUDANÇA 3
      
      # Diz ao broker para usar este listener para se comunicar (mesmo internamente)
      KAFKA_INTER_BROKER_LISTENER_NAME: ALL # <-- MUDANÇA 4

      # Configurações básicas
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_DIRS: /var/lib/kafka/data

      # Logging
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"

    deploy:
      placement:
        constraints: [node.role == manager]

    tmpfs:
      - /var/lib/kafka/data
